apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: java-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: java-service
          image: public.ecr.aws/nginx/nginx:1.24
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      #     volumeMounts:
      #       - name: content
      #         mountPath: /usr/share/nginx/html
      #         readOnly: true
      # volumes:
      #   - name: content
      #     configMap:
      #       name: java-content
  strategy:
    blueGreen:
      activeService: java-service-active
      previewService: java-service-preview
      autoPromotionEnabled: false # Pauses indefinitely for manual/Keptn promotion
