apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: python-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      containers:
        - name: python-service
          image: public.ecr.aws/docker/library/httpd:2.4.50 ## 2.4.50
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
              readOnly: true
          # --- LIVENESS PROBE ---
          # Checks if the container is deadlocked. If it fails 3 times, Kubernetes restarts it.
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30 # Give the JVM time to spin up
            periodSeconds: 15 # Check every 15 seconds
            timeoutSeconds: 3 # Must respond within 3 seconds
            failureThreshold: 3 # Restart after 3 consecutive failures

          # --- READINESS PROBE ---
          # Checks if the app is ready for traffic. Argo Rollouts waits for this.
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10 # Check more frequently than liveness
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1 # Needs 1 success to be marked Ready
      volumes:
        - name: content
          configMap:
            name: python-content
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s } # auto-advances after 30 seconds
        - setWeight: 50
        - pause: { duration: 1m } # Auto-advances after 1 minute
        - setWeight: 75
        - pause: { duration: 30s } # Auto-advances after 30 seconds
