# Example for apps/python-service/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - configmap.yaml

patches:
  - patch: |
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: java-service
      spec:
        strategy:
          blueGreen:
            prePromotionAnalysis:
              args:
              - name: url
                value: 'http://java-service-preview.dev.svc.cluster.local:80/'
            postPromotionAnalysis:
              args:
              - name: url
                value: 'http://java-service-active.dev.svc.cluster.local:80/'
