apiVersion: v1
kind: ConfigMap
metadata:
  name: python-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>python-prod</title>
    </head>
    <body>

    <h1>python-prod</h1>

    </body>
    </html>
