# Example for apps/python-service/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- configmap.yaml
images:
- name: public.ecr.aws/docker/library/httpd
  newTag: 2.4.66
